import { type RouteConfig, index, route } from "@react-router/dev/routes";
export default [
  index("routes/home.tsx"),
  route("method", "routes/method.tsx"),
  route("on", "routes/on.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("assessment", "routes/assessment.tsx"),
  route("studios", "routes/studios.tsx"),
  route("studios/:slug", "routes/studio-detail.tsx"),
  route("programs/:slug", "routes/program-landing.tsx"),
  route("blog", "routes/blog.tsx"),
  route("contact", "routes/contact.tsx"),
  route("privacy", "routes/legal.tsx", { id: "privacy" }),
  route("terms", "routes/legal.tsx", { id: "terms" }),
  route("admin/login", "routes/admin-login.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/leads", "routes/admin-leads.tsx"),
  route("admin/blog", "routes/admin-blog.tsx"),
  route("admin/blog/:id", "routes/admin-blog-edit.tsx"),
  route("admin/programs", "routes/admin-programs.tsx"),
] satisfies RouteConfig;
